# MCU name
MCU = atmega32u4

# Bootloader selection
BOOTLOADER = qmk-dfu
BOOTMAGIC_ENABLE = yes

SPLIT_KEYBOARD = yes
LTO_ENABLE := yes
RGBLIGHT_ENABLE = yes
RGBLIGHT_STARTUP_ANIMATION = yes
OLED_ENABLE = no
AUDIO_ENABLE = no
ENCODER_ENABLE = no
# VIA_ENABLE = yes
